DB_CONNECTION = "sqlite:///animals.db"
BREED_TRAITS_PATH = "data/breed_traits.csv"
MODEL_PATH = "src/recommender/model.pkl"
TRAITS_TRANSLATION_PATH = "data/trait_translation.csv"
BREED_RANK_PATH = "data/breed_rank.csv"
TRAITS_DESCRIPTION_PATH = "data/trait_description.csv"
