DB_CONNECTION = "sqlite:///animals.db"
BREED_TRAITS_PATH = "DogMatch/data/breed_traits.csv"
MODEL_PATH = "DogMatch/src/recommender/model.pkl"
TRAITS_TRANSLATION_PATH = "DogMatch/data/trait_translation.csv"
BREED_RANK_PATH = "DogMatch/data/breed_rank.csv"
